name: Build KitoMarket Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # permite lanzarlo manualmente desde GitHub

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install customtkinter pyinstaller pillow

      - name: Construir EXE
        run: |
          pyinstaller --onefile --windowed --icon=KitoLogo.ico --add-data "KitoLogo.ico;." --add-data "KitoLogo.png;." --name KitoMarketPro minimarket_app.py

      - name: Subir EXE como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: KitoMarketPro-Windows
          path: dist/KitoMarketPro.exe
